# Generated by Django 6.0.4 on 2026-05-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='price',
            new_name='distance',
        ),
    ]
