# Generated by Django 6.0.4 on 2026-05-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ride', '0002_rename_price_ride_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
