# Generated by Django 6.0.4 on 2026-05-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0002_passenger_number_of_rides'),
        ('Ride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date_time', models.DateTimeField(auto_now_add=True)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.passenger')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ride.ride')),
            ],
        ),
    ]
