# Generated by Django 6.0.4 on 2026-05-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='passenger_id',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='ride_id',
            new_name='ride',
        ),
    ]
