# Generated by Django 6.0.4 on 2026-05-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_rename_passenger_id_booking_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=20.0),
        ),
    ]
