# Generated by Django 6.0.4 on 2026-05-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='number_of_rides',
            field=models.IntegerField(default=0),
        ),
    ]
